[package]
name = "bevy-async-ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.12", git = "https://github.com/bevyengine/bevy", rev="951c9bb1a25caddc97ac69bbe8a2937f97227e90", default-features = false }
async-channel = "1"

[dev-dependencies]
futures-lite = "1"
