[package]
name = "bevy-async-ecs"
version = "0.1.0"
authors = ["Mark Old <dlom234@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Asynchronous interface for Bevy ECS"
repository = "https://github.com/dlom/bevy-async-ecs"
keywords = ["bevy", "ecs", "async", "game"]
categories = ["game-engines", "asynchronous"]

[dependencies]
bevy_app = { version = "0.12.1", default-features = false }
bevy_core = { version = "0.12.1", default-features = false }
bevy_ecs = { version = "0.12.1", default-features = false }
bevy_hierarchy = { version = "0.12.1", default-features = false }
bevy_reflect = { version = "0.12.1", default-features = false }
async-channel = "2"

[dev-dependencies]
bevy = "0.12.1"
futures-lite = "2"
